name: Test branch
on: push

jobs:
  ci:
    name: Run Build and check output is checked-in
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: 'Build'
      run: |
        npm install
        npm run build
    - name: Check no files have changes
      run: git diff --exit-code
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Install NPM Packages
      run: |
        npm install
    - name: Run Unit Tests
      run: |
        npm run test -- --coverage
    - name: Check Linting
      run: |
        npm run lint
    - name: Submit to CodeCov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage/lcov.info
        fail_ci_if_error: true
