name: Libyear
on: push

jobs:
  libyear:
    name: Libyear
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: 'Install NPM Packages'
      run: |
        npm install
    - name: Run libyear action
      uses: ./
